### ISSUE TITLE
cargo not found in PATH. Please install rust

### ISSUE THREAD

**Issue by garysdevil** [polkascan/polkascan-os#18]
docker-compose -p kusama -f docker-compose.kusama-full.yml up --build

![图片](https://user-images.githubusercontent.com/41293784/83408964-17ab7500-a446-11ea-9147-5aedbe6665e5.png)

**Comment by vshvsh** [comment]
Check out #19 we made a workaround.

**Comment by arjanz** [comment]
We updated the Docker base image to match the Polkascan.io one, for some reason the precompiled RUST bindings couldn't be used for the Python-alpine image. Sorry for the hick-up, should be working again!
