### ISSUE TITLE
Missed block in DB when running on Polkadot CC1

### ISSUE THREAD

**Issue by togran** [polkascan/polkascan-os#20]
Occasionally DB misses some blocks for an unidentified reason, and harvester cease to check blocks with this line:
harvester-worker_1   | [2020-06-04 11:18:43,394: INFO/ForkPoolWorker-1] Task app.tasks.start_sequencer[d10613af-4597-4529-a304-aca5333e11bf] succeeded in 0.329269085001215s: {'result': 'Block #125428 is missing.. stopping check '}
I have tried to restart whole process about 10 times, and none was successfull
How can I make polkascan to populate missed blocks?
Why it can miss it?

[docker-compose.polkadot-full.yml.txt](https://github.com/polkascan/polkascan-os/files/4729636/docker-compose.polkadot-full.yml.txt)
commit bd5ed4b

**Comment by arjanz** [comment]
Sometimes after an interrupted run there could be a gap in the process queue, which (at the moment) needs to be manually started again.  

You can check this at URL: http://127.0.0.1:8080/polkadot/harvester/admin (or http://127.0.0.1:8080/kusama/harvester/admin for Kusama) and then process the 'Process harvester queue' button.

We recently updated the API endpoint for the process queue, so you might have to pull the update first.

**Comment by vshvsh** [comment]
Thanks, it helped!
