### ISSUE TITLE
HarvesterCouldNotAddBlock Error

### ISSUE THREAD

**Issue by ToufeeqP** [polkascan/polkascan-os#37]
We have customised blockchain based on substrate 2.0.  And we have some custom types as well, for which we have created a separate json file & configured it & its working I believe. Though I faced a lot of other issues, I managed to fix them all. I am running our node locally & able to fetch blocks from the node via RPC. But while processing the blocks, I am getting the following error: 

`Traceback (most recent call last):
  File "/usr/src/app/app/tasks.py", line 110, in accumulate_block_recursive
    block = harvester.add_block(block_hash)
  File "/usr/src/app/app/processors/converters.py", line 451, in add_block
    self.process_metadata(self.substrate.runtime_version, block_hash)
  File "/usr/src/app/app/processors/converters.py", line 238, in process_metadata
    module_id=module.get_identifier()
AttributeError: 'MetadataV12Module' object has no attribute 'get_identifier'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 375, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/app/tasks.py", line 70, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 632, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/app/tasks.py", line 137, in accumulate_block_recursive
    raise HarvesterCouldNotAddBlock(block_hash) from exc
app.processors.converters.HarvesterCouldNotAddBlock: 0xa0774828a80faacac9ce411b60bcaa29370699b012f39722317ed76217635f9d`

Please let me know what could be the issue? Is it related to type registry, or some other issue?

**Comment by arjanz** [comment]
> AttributeError: 'MetadataV12Module' object has no attribute 'get_identifier'
This issue should already been fixed since https://github.com/polkascan/py-scale-codec/commit/aa939d3aa8fe36d8d7fda4446966343d19cd19f5 ..

Could be the GIT submodules weren't updated, but just to be sure I just pushed a dependency version bump to latest version of scalecodec and py-substrate-interface. As usual you can update this with `git submodule update --init --recursive`

Let me know if you still have problems..

**Comment by ToufeeqP** [comment]
Thanks for the reply. I have already updated submodules using `git submodule update --init --recursive` command. And I have confirmed it manually as well. What else could be the issue?

**Comment by ToufeeqP** [comment]
After I pulled the fresh code from the master branch & updated all submodules, now I am getting a different error. I have custom type in blockchain Did = [u8; 32] & updated the same in `custom_types.json` file. And my custom pallet emits an event such as DidCreated(Did). While processing the block which has this event, I am getting the following error:
`[2020-12-17 08:28:55,128: ERROR/ForkPoolWorker-4] Task app.tasks.accumulate_block_recursive[618a1e3c-15b5-4aac-b415-bb682360f213] raised unexpected: HarvesterCouldNotAddBlock('0xf02950133851610e9c7d6142c4d991bad5e79b12e9d98aafefd877a54cf4eb7f')
harvester-worker_1   | Traceback (most recent call last):
harvester-worker_1   |   File "/usr/src/app/app/tasks.py", line 116, in accumulate_block_recursive
harvester-worker_1   |     block = harvester.add_block(block_hash)
harvester-worker_1   |   File "/usr/src/app/app/processors/converters.py", line 534, in add_block
harvester-worker_1   |     events_decoder = self.substrate.get_block_events(block_hash, self.metadata_store[parent_spec_version])
harvester-worker_1   |   File "/usr/src/app/py-substrate-interface/substrateinterface/__init__.py", line 841, in get_block_events
harvester-worker_1   |     events_decoder.decode()
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 301, in decode
harvester-worker_1   |     self.value = self.process()
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/block.py", line 317, in process
harvester-worker_1   |     element = self.process_type('EventRecord', metadata=self.metadata)
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 359, in process_type
harvester-worker_1   |     obj.decode(check_remaining=False)
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 301, in decode
harvester-worker_1   |     self.value = self.process()
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/block.py", line 401, in process
harvester-worker_1   |     arg_type_obj = self.process_type(arg_type)
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 358, in process_type
harvester-worker_1   |     obj = self.get_decoder_class(type_string, self.data, runtime_config=self.runtime_config, **kwargs)
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 354, in get_decoder_class
harvester-worker_1   |     raise NotImplementedError('Decoder class for "{}" not found'.format(type_string))
harvester-worker_1   | NotImplementedError: Decoder class for "Did" not found
harvester-worker_1   | 
harvester-worker_1   | The above exception was the direct cause of the following exception:
harvester-worker_1   | 
harvester-worker_1   | Traceback (most recent call last):
harvester-worker_1   |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
harvester-worker_1   |     R = retval = fun(*args, **kwargs)
harvester-worker_1   |   File "/usr/src/app/app/tasks.py", line 70, in __call__
harvester-worker_1   |     return super().__call__(*args, **kwargs)
harvester-worker_1   |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 648, in __protected_call__
harvester-worker_1   |     return self.run(*args, **kwargs)
harvester-worker_1   |   File "/usr/src/app/app/tasks.py", line 143, in accumulate_block_recursive
harvester-worker_1   |     raise HarvesterCouldNotAddBlock(block_hash) from exc
harvester-worker_1   | app.processors.converters.HarvesterCouldNotAddBlock: 0xf02950133851610e9c7d6142c4d991bad5e79b12e9d98aafefd877a54cf4eb7f`

**Comment by arjanz** [comment]
Did you made the entry in the JSON file like this?

```
...
"types": {
    "Did": "[u8; 32]"
...
```

And did you referenced to this `custom_types.json` in the env of the docker-compose file? (`TYPE_REGISTRY_FILE=app/type_registry/custom_types.json`)

**Comment by ToufeeqP** [comment]
Yes, I did that.

**Comment by ToufeeqP** [comment]
Sorry, i had a typo. Instead of types, I had put type. After fixing this typo, I was getting the `AttributeError: 'GenericMultiAddress' object has no attribute 'account_length'` error. But I found one latest commit in the scale-codec repo in which this GenericMultiAddress class has been updated.  I used that code, & running fine. Thanks for your time.
