### ISSUE TITLE
api-01.polkascan.io not working

### ISSUE THREAD

**Issue by true-eye** [polkascan/polkascan-os#43]
I followed the `Quick deployment of Polkascan` and it runs on localhost:8080. But it doesn't load any data. If I inspect the network, it calls `api-01.polkascan.io` but it fails.

Please help me!
Thanks

**Comment by arjanz** [comment]
The API endpoint has been updated, please update to the latest version

**Comment by true-eye** [comment]
> The API endpoints has been updated, please update to the latest version

I use the latest version v0.6.2 but it points to `api-01.polkascan.io`

**Comment by arjanz** [comment]
Ah I see.. we forgot to make a tag this release, it was only in master (which you can also switch to for latest updates). Try checking out v0.6.3 now

**Comment by true-eye** [comment]
Thank you
